//
//  AIService.swift
//  macOSShaderCanvas
//
//  Async networking layer for AI-powered features: shader assistance chat
//  and automated tutorial generation.
//
//  SUPPORTED PROVIDERS:
//  ────────────────────
//  • OpenAI    — GPT-4o, GPT-4.1, etc. via /v1/chat/completions
//  • Anthropic — Claude Sonnet/Opus via /v1/messages
//  • Gemini    — Gemini 2.5 Flash/Pro via generateContent
//
//  ARCHITECTURE:
//  ─────────────
//  AIService is an `actor` (not a class) for built-in thread safety.
//  All methods can be called from any thread without data races.
//  The singleton `shared` instance is used throughout the app.
//
//  Two main entry points:
//  1. chat()             — multi-turn conversation with workspace context
//  2. generateTutorial() — produces structured TutorialStep JSON
//
//  ERROR HANDLING:
//  ───────────────
//  All API errors are wrapped in the AIError enum with user-friendly messages.
//  Network errors, invalid responses, and missing API keys are handled gracefully.
//

import Foundation

/// Thread-safe AI service that handles communication with LLM APIs.
///
/// Uses Swift's `actor` model to guarantee all internal state is accessed
/// serially, eliminating data races without manual locking.
actor AIService {

    /// Singleton instance. Use `await AIService.shared.chat(...)`.
    static let shared = AIService()

    private let session = URLSession.shared

    // MARK: - Public API

    /// Sends a chat message as an intelligent Agent that can analyze the request,
    /// decide whether it can be fulfilled by adding/modifying shader layers, and
    /// return structured actions alongside an explanation.
    ///
    /// The Agent receives the full workspace context (active shaders, data flow config)
    /// and responds with a structured `AgentResponse` containing:
    /// - An explanation in the user's language
    /// - Concrete layer operations (add/modify) if the request is achievable
    /// - Technical barriers if the request cannot be fulfilled
    ///
    /// Falls back to plain text if the model's response cannot be parsed as JSON.
    func agentChat(messages: [ChatMessage], context: String, dataFlowDescription: String, settings: AISettings) async throws -> AgentResponse {
        let systemPrompt = """
        You are a Metal Shading Language (MSL) expert assistant embedded in a real-time shader editor app.
        You are an intelligent Agent that can directly add new shader layers or modify existing ones in the user's workspace.

        RESPONSE FORMAT: You MUST respond with ONLY a valid JSON object. No markdown fences, no extra text.
        {
          "canFulfill": true/false,
          "explanation": "Your explanation to the user (same language as user)",
          "actions": [
            {
              "type": "addLayer",
              "category": "vertex|fragment|fullscreen",
              "name": "Descriptive Layer Name",
              "code": "complete compilable MSL code"
            }
          ],
          "barriers": ["technical barrier 1", "barrier 2"]
        }
        Set "barriers" to null when canFulfill is true. Set "actions" to [] when no layer changes are needed.
        For modifying existing layers, use type "modifyLayer" with additional field "targetLayerName" (exact name of the existing layer).

        CURRENT WORKSPACE:
        \(context)

        DATA FLOW CONFIGURATION:
        \(dataFlowDescription)

        SHADER CODE RULES:

        Vertex & Fragment shaders (mesh shaders):
        - Struct definitions (VertexIn, VertexOut, Uniforms) are AUTO-GENERATED by the Data Flow system.
        - DO NOT include #include <metal_stdlib>, using namespace metal, or struct definitions.
        - Only write the shader function(s).
        - Vertex entry: vertex VertexOut vertex_main(VertexIn in [[stage_in]], constant Uniforms &uniforms [[buffer(1)]])
        - Fragment entry: fragment float4 fragment_main(VertexOut in [[stage_in]])
        - Available Uniforms fields: mvpMatrix (float4x4), modelMatrix (float4x4), normalMatrix (float4x4), cameraPosition (float4, xyz=world pos), time (float)

        Fullscreen (post-processing) shaders:
        - MUST be self-contained: include #include <metal_stdlib>, using namespace metal, and ALL struct definitions.
        - MUST define BOTH vertex_main (fullscreen triangle from vertex_id) AND fragment_main.
        - Reads previous pass via: texture2d<float> inTexture [[texture(0)]]
        - VertexOut must have: position [[position]], texCoord (float2), time (float).
        - Uniforms: { float4x4 modelViewProjectionMatrix; float time; }

        User parameters (optional): Add // @param _name type default [min max] at the top for auto UI controls.
        Example: // @param _intensity float 0.5 0.0 1.0  (creates a slider)
        Example: // @param _tint color 1.0 0.5 0.2        (creates a color picker)

        CAPABILITIES (canFulfill = true):
        ✓ Any shading model (Lambert, Phong, Blinn-Phong, Toon/Cel, PBR approximation, Gooch, Fresnel, etc.)
        ✓ Vertex deformations (wave, twist, inflate, morph, noise-based displacement, etc.)
        ✓ Post-processing effects (blur, bloom, vignette, color grading, edge detection, distortion, etc.)
        ✓ Chaining multiple fullscreen passes for complex effect pipelines
        ✓ Time-animated effects using uniforms.time
        ✓ Combining vertex + fragment + fullscreen layers for complete visual effects

        LIMITATIONS (canFulfill = false, explain barriers):
        ✗ Shadow mapping — requires a separate depth-only render pass from light's perspective
        ✗ Screen-space reflections (SSR) — requires depth buffer texture input not available
        ✗ Ray tracing / path tracing — requires compute shaders or RT API not in current pipeline
        ✗ External texture sampling — only inTexture (from previous pass) available in fullscreen
        ✗ Geometry / tessellation shaders — not available in this pipeline
        ✗ Multiple render targets (MRT) — pipeline outputs to a single color attachment
        ✗ Stencil buffer operations — not exposed in current pipeline
        ✗ Compute shaders — not in current rendering pipeline

        IMPORTANT:
        - All generated shader code MUST compile. Verify mentally before outputting.
        - Answer in the SAME LANGUAGE the user writes in.
        - Be concise in explanations.
        - Give layers descriptive names reflecting their purpose.
        - If the request needs multiple layers, add all needed layers.
        - In conversation history, your previous responses appear as plain text (the JSON was already processed). Always respond with JSON format regardless.
        """
        let rawResponse: String
        switch settings.selectedProvider {
        case .openai:   rawResponse = try await callOpenAI(system: systemPrompt, messages: messages, settings: settings)
        case .anthropic: rawResponse = try await callAnthropic(system: systemPrompt, messages: messages, settings: settings)
        case .gemini:   rawResponse = try await callGemini(system: systemPrompt, messages: messages, settings: settings)
        }
        do {
            return try parseAgentResponse(from: rawResponse)
        } catch {
            return AgentResponse.plainText(rawResponse)
        }
    }

    /// Generates a structured tutorial from a topic description.
    ///
    /// The AI is instructed to output a raw JSON array of tutorial steps.
    /// Each step includes starter code (with TODO markers) and a complete solution.
    /// The response is parsed into `[TutorialStep]` and loaded into the tutorial panel.
    ///
    /// - Parameters:
    ///   - topic: A natural-language description of what to teach (e.g. "Build a PBR shader").
    ///   - settings: The current AI provider configuration.
    /// - Returns: An array of `TutorialStep` objects ready for the tutorial panel.
    /// - Throws: `AIError` if the API call fails or the response cannot be parsed.
    func generateTutorial(topic: String, settings: AISettings) async throws -> [TutorialStep] {
        let systemPrompt = """
        You are a Metal Shading Language expert educator. Generate a step-by-step shader tutorial.
        Output ONLY a valid JSON array (no markdown). Each element:
        { "title","subtitle","instructions","goal","hint","category":"fragment|vertex|fullscreen","starterCode","solutionCode" }
        All shaders must compile. Include #include <metal_stdlib> and using namespace metal.
        Vertex: entry vertex_main, VertexIn attrs 0/1/2, Uniforms buffer(1). Fragment: entry fragment_main, VertexOut.
        Fullscreen: both vertex_main (fullscreen triangle) + fragment_main with inTexture [[texture(0)]].
        starterCode should have // TODO comments. Generate 3-6 progressive steps.
        """
        let userMsg = ChatMessage(role: .user, content: "Create a tutorial about: \(topic)")
        let response: String
        switch settings.selectedProvider {
        case .openai:   response = try await callOpenAI(system: systemPrompt, messages: [userMsg], settings: settings)
        case .anthropic: response = try await callAnthropic(system: systemPrompt, messages: [userMsg], settings: settings)
        case .gemini:   response = try await callGemini(system: systemPrompt, messages: [userMsg], settings: settings)
        }
        return try parseTutorialSteps(from: response)
    }

    // MARK: - Provider Implementations

    /// Calls the OpenAI Chat Completions API.
    private func callOpenAI(system: String, messages: [ChatMessage], settings: AISettings) async throws -> String {
        var req = URLRequest(url: URL(string: "https://api.openai.com/v1/chat/completions")!)
        req.httpMethod = "POST"
        req.setValue("Bearer \(settings.openAIKey)", forHTTPHeaderField: "Authorization")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var msgs: [[String: String]] = [["role": "system", "content": system]]
        for m in messages { msgs.append(["role": m.role == .user ? "user" : "assistant", "content": m.content]) }
        req.httpBody = try JSONSerialization.data(withJSONObject: ["model": settings.openAIModel, "messages": msgs, "max_tokens": 4096] as [String: Any])
        let (data, resp) = try await session.data(for: req)
        try check(resp, data: data, provider: "OpenAI")
        let json = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        guard let choices = json?["choices"] as? [[String: Any]], let msg = choices.first?["message"] as? [String: Any], let content = msg["content"] as? String else { throw AIError.invalidResponse("OpenAI") }
        return content
    }

    /// Calls the Anthropic Messages API.
    private func callAnthropic(system: String, messages: [ChatMessage], settings: AISettings) async throws -> String {
        var req = URLRequest(url: URL(string: "https://api.anthropic.com/v1/messages")!)
        req.httpMethod = "POST"
        req.setValue(settings.anthropicKey, forHTTPHeaderField: "x-api-key")
        req.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var msgs: [[String: String]] = []
        for m in messages { msgs.append(["role": m.role == .user ? "user" : "assistant", "content": m.content]) }
        req.httpBody = try JSONSerialization.data(withJSONObject: ["model": settings.anthropicModel, "max_tokens": 4096, "system": system, "messages": msgs] as [String: Any])
        let (data, resp) = try await session.data(for: req)
        try check(resp, data: data, provider: "Anthropic")
        let json = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        guard let content = json?["content"] as? [[String: Any]], let text = content.first?["text"] as? String else { throw AIError.invalidResponse("Anthropic") }
        return text
    }

    /// Calls the Google Gemini generateContent API.
    private func callGemini(system: String, messages: [ChatMessage], settings: AISettings) async throws -> String {
        let model = settings.geminiModel
        var req = URLRequest(url: URL(string: "https://generativelanguage.googleapis.com/v1beta/models/\(model):generateContent?key=\(settings.geminiKey)")!)
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        var contents: [[String: Any]] = []
        for m in messages { contents.append(["role": m.role == .user ? "user" : "model", "parts": [["text": m.content]]]) }
        req.httpBody = try JSONSerialization.data(withJSONObject: ["contents": contents, "systemInstruction": ["parts": [["text": system]]]] as [String: Any])
        let (data, resp) = try await session.data(for: req)
        try check(resp, data: data, provider: "Gemini")
        let json = try JSONSerialization.jsonObject(with: data) as? [String: Any]
        guard let cands = json?["candidates"] as? [[String: Any]], let co = cands.first?["content"] as? [String: Any], let parts = co["parts"] as? [[String: Any]], let text = parts.first?["text"] as? String else { throw AIError.invalidResponse("Gemini") }
        return text
    }

    // MARK: - Helpers

    /// Validates the HTTP response status code. Throws on non-2xx responses.
    private func check(_ response: URLResponse, data: Data, provider: String) throws {
        guard let http = response as? HTTPURLResponse, (200...299).contains(http.statusCode) else {
            let body = String(data: data, encoding: .utf8) ?? ""
            throw AIError.apiError(provider: provider, status: (response as? HTTPURLResponse)?.statusCode ?? 0, message: body)
        }
    }

    /// Parses a JSON array string from the AI response into TutorialStep objects.
    ///
    /// Handles common AI response quirks:
    /// - Strips markdown code fences if present
    /// - Extracts the JSON array from surrounding text
    /// - Validates all required fields are present
    private func parseTutorialSteps(from text: String) throws -> [TutorialStep] {
        var s = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if let a = s.range(of: "["), let b = s.range(of: "]", options: .backwards) { s = String(s[a.lowerBound...b.upperBound]) }
        guard let data = s.data(using: .utf8), let arr = try JSONSerialization.jsonObject(with: data) as? [[String: Any]] else { throw AIError.invalidResponse("parse") }
        var steps: [TutorialStep] = []
        for (i, item) in arr.enumerated() {
            guard let title = item["title"] as? String, let sub = item["subtitle"] as? String, let inst = item["instructions"] as? String, let goal = item["goal"] as? String, let hint = item["hint"] as? String, let catStr = item["category"] as? String, let starter = item["starterCode"] as? String, let solution = item["solutionCode"] as? String else { continue }
            let cat: ShaderCategory = catStr.lowercased() == "vertex" ? .vertex : catStr.lowercased() == "fullscreen" ? .fullscreen : .fragment
            steps.append(TutorialStep(id: i, title: title, subtitle: sub, instructions: inst, goal: goal, hint: hint, category: cat, starterCode: starter, solutionCode: solution))
        }
        guard !steps.isEmpty else { throw AIError.invalidResponse("0 steps") }
        return steps
    }

    /// Parses a structured AgentResponse from the AI's raw text output.
    ///
    /// Handles common formatting quirks:
    /// - Strips markdown code fences (```json ... ```) if present
    /// - Finds the outermost JSON object using brace-depth counting
    ///   (correctly handles nested braces inside string values like shader code)
    /// - Falls back with a thrown error if no valid JSON object can be extracted
    private func parseAgentResponse(from text: String) throws -> AgentResponse {
        var cleaned = text.trimmingCharacters(in: .whitespacesAndNewlines)

        // Strip markdown code fences
        let fencePattern = #"```(?:json)?\s*([\s\S]*?)```"#
        if let regex = try? NSRegularExpression(pattern: fencePattern),
           let match = regex.firstMatch(in: cleaned, range: NSRange(cleaned.startIndex..., in: cleaned)),
           let range = Range(match.range(at: 1), in: cleaned) {
            cleaned = String(cleaned[range]).trimmingCharacters(in: .whitespacesAndNewlines)
        }

        // Find outermost JSON object via brace-depth counting
        guard let startIdx = cleaned.firstIndex(of: "{") else {
            throw AIError.invalidResponse("No JSON object found in agent response")
        }
        var depth = 0
        var inString = false
        var escaped = false
        var endIdx = cleaned.endIndex

        for i in cleaned.indices[startIdx...] {
            let c = cleaned[i]
            if escaped { escaped = false; continue }
            if c == "\\" && inString { escaped = true; continue }
            if c == "\"" { inString.toggle(); continue }
            if !inString {
                if c == "{" { depth += 1 }
                else if c == "}" {
                    depth -= 1
                    if depth == 0 { endIdx = cleaned.index(after: i); break }
                }
            }
        }

        let jsonString = String(cleaned[startIdx..<endIdx])
        guard let data = jsonString.data(using: .utf8) else {
            throw AIError.invalidResponse("Failed to encode agent JSON to data")
        }
        return try JSONDecoder().decode(AgentResponse.self, from: data)
    }
}

// MARK: - AI Error Types

/// Errors that can occur during AI API interactions.
enum AIError: LocalizedError {
    /// No API key has been configured for the selected provider.
    case notConfigured

    /// The API returned a non-2xx HTTP status code.
    case apiError(provider: String, status: Int, message: String)

    /// The API response could not be parsed into the expected format.
    case invalidResponse(String)

    var errorDescription: String? {
        switch self {
        case .notConfigured: return "No API key configured."
        case .apiError(let p, let s, let m): return "\(p) error (\(s)): \(String(m.prefix(200)))"
        case .invalidResponse(let d): return "Invalid AI response: \(d)"
        }
    }
}
